services:
  postgres:
    image: postgres:17-alpine
    container_name: "nojoh-app-db"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "nojoh"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nojoh-network

volumes:
  pgdata:

networks:
  nojoh-network:
    driver: bridge
