services:
  nginx:
    image: nginx:alpine
    container_name: nojoh-proxy
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host

  postgres:
    image: postgres:17-alpine
    container_name: "nojoh-db"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "nojoh"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nojoh-network

volumes:
  pgdata:

networks:
  nojoh-network:
    driver: bridge
