import Navbar from "@/components/layout/Navbar";
import { ReactQueryClientProvider } from "@/lib/ReactQueryClientProvider";
import "@/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import { dmSerif, jost } from "./fonts";

export const metadata: Metadata = {
  title: "Nojoh App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="fr">
        <body className={`${jost.variable} ${dmSerif.variable} antialiased`}>
          <ReactQueryClientProvider>
            <div className="min-h-screen max-w-screen overflow-x-hidden">
              <Navbar />
              <main className="px-6">
                <Toaster />
                {children}
              </main>
            </div>
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
