import Navbar from "@/components/layout/Navbar";
import { ReactQueryClientProvider } from "@/lib/ReactQueryClientProvider";
import "@/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import { dmSerif, jost, workSans } from "./fonts";

export const metadata: Metadata = {
  title: "Nojoh App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="fr">
        <body
          className={`${jost.variable} ${dmSerif.variable} ${workSans.variable} antialiased`}
        >
          <ReactQueryClientProvider>
            <div className="flex h-screen w-screen overflow-hidden">
              <Navbar />
              <main className="flex-1 p-12">{children}</main>
              <Toaster />
            </div>
            <ReactQueryDevtools initialIsOpen={false} />
          </ReactQueryClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
